repos:
  - repo: https://github.com/sourcery-ai/sourcery
    rev: v0.9.5 # Get the latest tag from https://github.com/sourcery-ai/sourcery/tags
    hooks:
      - id: sourcery

  - repo: git://github.com/pre-commit/pre-commit-hooks
    rev: v0.9.2
    hooks:
      - id: check-added-large-files
        args: [ '--maxkb=500' ]
      - id: check-byte-order-marker
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-symlinks
      - id: debug-statements
      - id: detect-private-key

  - repo: local
    hooks:
      - id: isort
        name: isort-local
        entry: isort
        language: python
        types: [ python ]
        exclude: .+/(settings|migrations|venv)/.+
        pass_filenames: true
      - id: black
        name: black-local
        entry: black
        language: python
        types: [ python ]
        exclude: .+/(settings|migrations|venv)/.+
        pass_filenames: true
      - id: missing-migrations
        name: missing-migrations-local
        entry: python manage.py makemigrations --check --dry-run
        language: system
        always_run: true
        pass_filenames: false