# Generated by Django 4.1.6 on 2023-02-13 08:18

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="GeneratedImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("task_id", models.UUIDField()),
                ("host", models.CharField(blank=True, max_length=255, null=True)),
                ("duration", models.FloatField(null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("generated_at", models.DateTimeField(blank=True, null=True)),
                ("prompt", models.TextField()),
                ("seed", models.IntegerField(blank=True, null=True)),
                ("guidance_scale", models.FloatField(blank=True, null=True)),
                ("num_inference_steps", models.IntegerField(blank=True, null=True)),
                ("height", models.IntegerField(blank=True, null=True)),
                ("width", models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
