# Generated by Django 4.1.6 on 2023-02-17 01:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("generate", "0002_renderworkerdevice"),
    ]

    operations = [
        migrations.AddField(
            model_name="generatedimage",
            name="model",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
