# Generated by Django 4.1.6 on 2023-02-17 04:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("generate", "0003_generatedimage_model"),
    ]

    operations = [
        migrations.AddField(
            model_name="generatedimage",
            name="error",
            field=models.BooleanField(default=False),
        ),
    ]
