# Generated by Django 4.1.6 on 2023-02-18 01:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("generate", "0004_generatedimage_error"),
    ]

    operations = [
        migrations.AddField(
            model_name="generatedimage",
            name="nsfw",
            field=models.BooleanField(default=False),
        ),
    ]
