# Generated by Django 4.1.6 on 2023-02-22 02:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("generate", "0005_generatedimage_nsfw"),
    ]

    operations = [
        migrations.AddField(
            model_name="generatedimage",
            name="negative_prompt",
            field=models.TextField(blank=True, null=True),
        ),
    ]
