# Generated by Django 3.2.18 on 2023-03-08 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generate', '0007_generatedimage_batch_number_generatedimage_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generatedimage',
            name='task_id',
            field=models.UUIDField(null=True),
        ),
    ]
