# Generated by Django 3.2.18 on 2023-03-08 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generate', '0008_alter_generatedimage_task_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='generatedimage',
            name='private',
            field=models.BooleanField(default=False),
        ),
    ]
