# Generated by Django 3.2.18 on 2023-03-09 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generate', '0009_generatedimage_private'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generatedimage',
            name='guidance_scale',
            field=models.FloatField(blank=True, default=7.5, null=True),
        ),
        migrations.AlterField(
            model_name='generatedimage',
            name='height',
            field=models.IntegerField(blank=True, default=512, null=True),
        ),
        migrations.AlterField(
            model_name='generatedimage',
            name='num_inference_steps',
            field=models.IntegerField(blank=True, default=50, null=True),
        ),
        migrations.AlterField(
            model_name='generatedimage',
            name='seed',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='generatedimage',
            name='width',
            field=models.IntegerField(blank=True, default=512, null=True),
        ),
    ]
