# Generated by Django 4.1.6 on 2023-02-21 04:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("model", "0003_unconditionalimagegenerationmodel"),
    ]

    operations = [
        migrations.CreateModel(
            name="ImageSegmentationModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("model_id", models.CharField(blank=True, max_length=255, null=True)),
                ("likes", models.IntegerField(blank=True, null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
